[theme]
primaryColor="#E50914"              # Netflix Red
backgroundColor="#141414"          # Netflix Dark Background
secondaryBackgroundColor="#1F1F1F" # Slightly lighter dark panel
textColor="#FFFFFF"                # Pure white text
font="sans serif"
