[theme]
primaryColor="#FA4616"              # Gators Orange
backgroundColor="#FFFFFF"          # White Background
secondaryBackgroundColor="#F1F1F1" # Light Grey
textColor="#0021A5"                # Gators Blue
font="sans serif"
